name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          # Cache installed packages
          cache: 'yarn'
          cache-dependency-path: 'packages/moda-visualiser/yarn.lock'

      - name: "Add auth details to npmrc"
        run : echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - name: "Set default registry to npm"
        run : echo "registry=https://registry.npmjs.org/" >> .npmrc
      - name: "Add scoped registry for moda"
        run : echo "@moda:registry=https://npm.pkg.github.com" >> .npmrc

      - run: yarn

      - name: Bootstrap lerna
        run: yarn ci:bootstrap

      - name: Build visualiser
        run: yarn build

      - run: yarn ci:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
